### ISSUE TITLE
Node.js usage

### ISSUE THREAD

**Issue by Vasile-Peste** [spotware/openapi-proto-messages#1]
Thank you for publishing the updated protobuf structure. What about updating also the Node.js usage examples?

Regards,
Vasile.

**Comment by afhacker** [comment]
We will release new code examples and libraries for Python, Go, and Nod.js but I cant give you an ETA.

**Comment by Vasile-Peste** [comment]
I have created a library for using the Open API and already handles protobuf messages and some logic that can be handled internally: https://github.com/Reiryoku-Technologies/cTrader-Layer.
