### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by diegobernardes** [spotware/openapi-proto-messages#13]
The last tag is _80_ and the different from master is just documentation and the Go package configuration at the proto files, which I need. It's possible to release a new tag? 

https://github.com/spotware/openapi-proto-messages/compare/80...main

**Comment by diegobernardes** [comment]
A [new tag](https://github.com/spotware/openapi-proto-messages/releases/tag/81) was released and it has this message at the changelog `Added Go package name`, the problem is, there is a [new commit](https://github.com/spotware/openapi-proto-messages/commit/aec27c3f66c48611ec437175eb37fa51d6893f10) that removes the go package. Any reason for that?

**Comment by baotang2118** [comment]
Same issue here, I am asking on PR.

https://github.com/spotware/openapi-proto-messages/pull/14#issuecomment-1583987947

**Comment by ShKhannanov** [comment]
@diegobernardes @baotang2118 Hi! Thank you for bringing our attention to this issue. Note that a new release has been drafted with the Go package option restored.

**Comment by baotang2118** [comment]
Thank you very much for quick action.
