### ISSUE TITLE
Provide clientId and clientSecret for testing

### ISSUE THREAD

**Issue by Vasile-Peste** [spotware/openapi-proto-messages#2]
The documentation at https://spotware.github.io/open-api-docs/protocol-buffers/

says using 

demo.ctraderapi.com:5035 for demo accounts
and live.ctraderapi.com:5035 for live accounts.

But meanhile my application submission gets approved, can you provide a clientId and clientSecret to test the API? With accountId and token as well.

Regards,
Vasile.

**Comment by afhacker** [comment]
We will approve your application today, and after it got approved you can start using Open API.
Regarding trading accounts, you can create as many trading accounts as you want to for free easily on Spotware cTrader beta, which you can download it from here: http://ctrader.com/download/
