### ISSUE TITLE
Open API Suggestions

### ISSUE THREAD

**Issue by Vasile-Peste** [spotware/openapi-proto-messages#3]
Hello there,
following my tests on Open API I would suggest:
- Create a request for retrieving the deals related to a position: given a position id, I would like to retrieve all the deals pointed to the position; This helps retrieving historic positions and their profit; Currently we have to request all deals in a time interval and then search for the ones linked to a position id. But this is imited to a certain interval of time and returns unused deals.
- Add leverage field for each symbol. The account leverage is only indicative: each symbol has its own leverage, and quite often leverage is different across asset classes;
- Create a request or add a field indicating if the market of a symbol is open. The scheduled openings/closings are not enough. Markets can be closed also on unexpected conditions and it's not very rare situation;
- I'm user (and big fan) of cTrader Web. On cTrader Web you indicate interesting information for deals. For example when I see the description of a deal, if the deal is opening volume then it's possibile to check the deals that closed the current deal/volume. On the opposite if the deal is closing volume then it's possibile to see the deals being closed by the current deal. It's possible to get this information also on Open API?
- Please create a Req to retrieve the last known tick with last known bid and ask for a symbol. Doing this now requires a lot of implementation work on client side.
- Why you don't provide request for retrieving equity and P&L for position? I understand that it can be inferred and calculated manually by using your interfaces, but this complicates implementations. I would suggest providing a "grossProfit" field for each position. For open positions it will provide the real time gross profit while for closed positions it will contain the gross profit at position close time. If you think this is expensive consumption of resources on your side I would say to probably rethink this as now calculating P&L from client side requires sending approximately 5-6 requests to your server. Doing this every second/tick could be expensive for you. I would like to add that you are already calculating swap and commission in deposit currency so why not provide unrealized gross profit directly calculated in deposit currency.

Some ambigous circumstances:
- The "closePositionDetail" field of a deal is defined if the deal is a closing deal. And this is the only field I can rely on to understand if the deal is a closing deal. What if the deal is rejected/missed? In this case the "closePositionDetail" field is still defined with the position id or not? Would be useful to track also failed deals and the relative target position.
- When making multiple asynchronous NewOrderReq, it's impossible to distinguish them during errors. When ExecutionEvent occurs we can associate event to request by using the order "label" or "comment" fields. But when errors occur it's not possible to associate a request to an event response.

Just some suggestions. I understand that your API already provides the fundamental functionalities to operate in markets.
I'm creating a framework for operating with NodeJS which uses Open API under the hood: I'm glad to contribute if you need me.

**Comment by afhacker** [comment]
Hi,
Here is our response for each of you abovementioned points:
* We will create a new request for getting a position deals
* Leverage will be added on next version
* Wrong. Schedule + holidays + tradingMode fully determine  trading possibilities. Nothing must be done on our side
* We will a request for getting a deal closing/opening deals
* You can use Spot event to get latest tick of a symbol
* We can't provide the real time P&L, because it will consume lots of resource on our side, you have to calculate it by yourself and we have a tutorial for it on API documentation
* To track rejected/missed deals you can use ProtoOAOrder.closingOrder, the closePositionDetail only appears in case of a successful closing deal
* In order to correctly identify responses, client must use unique ProtoMessage.clientMsgId for every request, sent to server. response (even error) will always contain same  clientMsgId. identification ussing label, comment, etc - is bad design

**Comment by Vasile-Peste** [comment]
Alright, regarding the last point. I would like to make an example.

I send two asynchronous order requests for EURUSD and XAUUSD symbols.
I get two events,

First one
```
{
  payloadType: 'PROTO_OA_ORDER_ERROR_EVENT',
  ctidTraderAccountId: 'xxx',
  errorCode: 'INVALID_VOLUME'  orderId: null,
  positionId: null,
  description: 'Trading is not available: Market is closed.'
}
```

Second one
```
{
  payloadType: 'PROTO_OA_ORDER_ERROR_EVENT',
  ctidTraderAccountId: 'xxx',
  errorCode: 'TIMEOUT_ERROR'  orderId: null,
  positionId: null,
  description: 'Trading is not available: Market is closed.'
}
```

How to associate each error response to the respective order request? How do I know if timeout is for EURUSD request or XAUUSD request?

**Comment by raul-gherman** [comment]
hey @Vasile-Peste you can use clientMsgId (at ProtoMessage level) -- if you set its value at request level, you will receive the same value at reply level, thus knowing exactly which reply was sent for which request

**Comment by Vasile-Peste** [comment]
> hey @Vasile-Peste you can use clientMsgId (at ProtoMessage level) -- if you set its value at request level, you will receive the same value at reply level, thus knowing exactly which reply was sent for which request

The example I made is not about request reply: it's about events, more precisely ProtoOAExecutionEvent, and they do not contain the clientMsgId of your request. I have just printed the server event after performing the order request, it's clear that the clientMsgId is not defined in the event.

**Comment by raul-gherman** [comment]
then the proper request, I guess, is to include clientMsgId (on backend side) in ProtoOAExecutionEvent that is dispatched (still, not sure how easy or hard it is to keep track -- once again, on backend side)

**Comment by afhacker** [comment]
> Alright, regarding the last point. I would like to make an example.
> 
> I send two asynchronous order requests for EURUSD and XAUUSD symbols. I get two events,
> 
> First one
> 
> ```
> {
>   payloadType: 'PROTO_OA_ORDER_ERROR_EVENT',
>   ctidTraderAccountId: 'xxx',
>   errorCode: 'INVALID_VOLUME'  orderId: null,
>   positionId: null,
>   description: 'Trading is not available: Market is closed.'
> }
> ```
> 
> Second one
> 
> ```
> {
>   payloadType: 'PROTO_OA_ORDER_ERROR_EVENT',
>   ctidTraderAccountId: 'xxx',
>   errorCode: 'TIMEOUT_ERROR'  orderId: null,
>   positionId: null,
>   description: 'Trading is not available: Market is closed.'
> }
> ```
> 
> How to associate each error response to the respective order request? How do I know if timeout is for EURUSD request or XAUUSD request?


Hi,

The PROTO_OA_ORDER_ERROR_EVENT returns the client message ID, here is an example:

payloadType: 2132
payload: "\022\022TRADING_BAD_VOLUME(\362\366\224\010::Order volume 1.00 is smaller than group minVolume=1000.00."
clientMsgId: "dsfdsf"

I send a new order request with invalid volume amount, and I received back the above response which has my client message ID.

**Comment by Vasile-Peste** [comment]
Clear! You are right, my bad cause I parse only the payload of incoming messages. Thank you for your patience, I'm looking forward to see your updates.
