### ISSUE TITLE
API Request

### ISSUE THREAD

**Issue by Vasile-Peste** [spotware/openapi-proto-messages#6]
Since you have introduced `ProtoOADealListByPositionIdReq` I would suggest creating also a `ProtoOAOrderListByPositionIdReq` which would allow reconstructing the entire life cycle of a position without the need to make deep search and perform many requests to `ProtoOAOrderListReq`.

I would also suggest a `ProtoOAPositionHistoryReq`
which should return all the the position orders, deals, swaps... all information about a position. This will avoid sending 5-10 requests to different ProtoOA methods for composing the whole situtation of a position.

Whad do you think?

Thank you for your great job 👏

**Comment by afhacker** [comment]
We already considering to add ProtoOAOrderListByPositionIdReq.
We will also add the DealListByOrderIdReq which will give you all the deals related to an order.

**Comment by Vasile-Peste** [comment]
Awesome, looking forward this update
